spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?allowPublicKeyRetrieval=true&amp&useSSL=false&amp&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: kolokolnin
spring.batch.jdbc.table-prefix: search_engine
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.jdbc.batch_size: 5
spring.jpa.properties.hibernate.order_inserts: true

server.port: 8080
spring.liquibase.enabled: true

url.default: /admin


useragent.name: searchBot/0.1

siteconfig:
  sites:
  - url: https://skillbox.ru
    name: Skillbox
  - url: https://www.lenta.ru
    name: Лента.ру




